function Hd = filtro_hamming
%FILTRO_HAMMING Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and Signal Processing Toolbox 8.4.
% Generated on: 03-May-2025 21:10:05

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 300;  % Sampling Frequency

N    = 10;       % Order
Fc   = 50;       % Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
