function Hd = filtro_blackman
%FILTRO_BLACKMAN Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and Signal Processing Toolbox 8.4.
% Generated on: 03-May-2025 21:03:50

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 300;  % Sampling Frequency

N    = 50;       % Order
Fc   = 20;       % Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = blackman(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
