function Hd = fir_kaiser_300_3400
%FIR_KAISER_300_3400 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 11-Apr-2025 21:08:09

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 300;  % Sampling Frequency

N    = 10;       % Order
Fc1  = 30;      % First Cutoff Frequency
Fc2  = 100;     % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag
Beta = 7.5;      % Window Parameter
% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
