/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.8 and Signal Processing Toolbox 8.4.
 * Generated on: 15-Apr-2025 12:24:40
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 101
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2020a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int8 filter coefficients.
 */
const int BL = 101;
const int8_T B[101] = {
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,    0,
      0,    0,    0,   -1,   -1,   -1,   -1,   -1,   -1,    0,    0,    0,
     -1,   -2,   -3,   -5,   -7,   -7,   -7,   -6,   -4,    0,    4,    8,
     12,   15,   15,   15,   12,    8,    4,    0,   -4,   -6,   -7,   -7,
     -7,   -5,   -3,   -2,   -1,    0,    0,    0,   -1,   -1,   -1,   -1,
     -1,   -1,    0,    0,    0,    0,    1,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0
};
